# Generated by Django 5.1.4 on 2025-02-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shoppingcart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel_number', models.CharField(max_length=15)),
                ('payment', models.CharField(choices=[('card', 'Cartão'), ('cash', 'Dinheiro')], max_length=10)),
                ('delivery', models.CharField(choices=[('pickup', 'Retirada na loja'), ('delivery', 'Entrega')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
