# Generated by Django 5.1.4 on 2025-02-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shoppingcart'),
        ),
    ]
