# Generated by Django 5.1.4 on 2025-02-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderinformation_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shoppingcart'),
        ),
    ]
