# Generated by Django 5.1.5 on 2025-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orderinformation_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Unidade', 'Unidade')], max_length=20)),
                ('category', models.CharField(choices=[('Carne', 'Carne'), ('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Legumes', 'Legumes')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
